#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# Must show all processes, for all users, including those which might not have a TTY
# Display a user-oriented format
# Show process hierarchy

ps -a -x -u -f
